### ISSUE TITLE
Unable to show form builder ?

### ISSUE THREAD

**Issue by i-internet** [mhunesi/yii2-formio#1]
```
 <?= FormioBuilderWidget::widget([
        'id' => 'example2',
            'model' => $model,
        'attribute' => 'form_data'
    ]);?>
```

Am i doing anything wrong ?

**Comment by mhunesi** [comment]
Hi, can you share with me error log.

**Comment by mhunesi** [comment]
For Example: https://github.com/mhunesi/yii2-formio/blob/master/src/views/forms/_form.php#L30 

$model is "mhunesi\formio\models\Forms" Model. data attribute is Form Builder JSON configuration. data attribute  default value is [];
Auto Generate Script new Formio.FormBuilder(document.getElementById('w1'), JSON.parse(String.raw`[]`), JSON.parse(String.raw`{"baseUrl":"http://yii.local/","projectUrl":"http://yii.local/"}`));
